// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bntbztbjxdspfdnhwixv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudGJ6dGJqeGRzcGZkbmh3aXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzQ3MDgsImV4cCI6MjA2MjAxMDcwOH0.yUR1l2GQmwd6EwAGhHOFBrYtEYhAOwQtXVL-IsplzLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);